layout_spectrum: 0.7458789917147985
typography_spectrum: 0.7896909056214781
color:
  brandStrength: 0.510080924068513
  lightness: 0.3252966744348518
  saturation: 0.370030430361149
  rhythmicContrast: 0.38165810725319727
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
name: Virtual Chill Studios Blog
url: 'https://blog.virtualchillstudios.xyz/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: VCS Home
    url: 'https://virtualchillstudios.xyz'
    type: external
title: VCS Blog
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/4a9baa4a28f402cc5f20022a4ad5a0baec13ef0e.png">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/4a9baa4a28f402cc5f20022a4ad5a0baec13ef0e.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Just Dev Things
github: true
